### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by yasyf** [kimberli/new-grad-offers#1]
Just jotting down my thoughts @kimberli!

> Unfortunately, I can't help you with any of that existential stuff

Don't undersell yourself you are so good with existential stuff 💯 

> I've been through my share of recruiting processes in my life

Would it be helpful to share examples of that for context? Also where you currently work?

> since you're not likely to encounter any glaring issues or sketchy conversations

I can think of lots of big companies where that's not true. high variance across both companies and teams.

> the most important thing to figure out is what stage company you'd like to be at

I think this is overstated sometimes. Yes there is a difference between 1000 and 5, but at a company of 30, depending on who you are and what the company is, you can shape an experience that feels like a 5 person seed company, or a 100 person series B company. having said that, totally on board with knowing what you want before you start interviewing - not enough people do that.

> there's always room to change paths

I would emphasize that at a small company, you don't even need to get a new job to do this. lots to be done on all fronts, great way to try a few things at once.

> when it would be appropiate to ask them

typo, and also you should never back from from asking anything. if people won't be transparent with an early hire, that's a bad signal.

> might not be comfortable putting answers to these questions in writing

cheers, yup. but they can still answer and should, verbally.

> Who are the investors? Are they people you trust to have done diligence on this business?

If you're an early hire you should ask to talk to the lead of the last round. Find out why she or he decided to put money into this company out of so many. Likewise for a key advisor.

Also, look at other investments the investors have made in the space? Are they known for making good bets in this field?

> things might look very different by the time you join the team

things *will* look very different

> Finally, try and think generally about the health of the business.

I think you're missing a really crucial section here on mission alignment and whether or not someone _cares_ about the work being done. You take a lot of hits working for a small company, especially on comp, and often that is mitigated by how strongly you feel about what the company is working on. Not true for every person or company, but really crucial nonetheless.

> How quickly is the business growing

Keep in mind things like this should be scaled and scoped for the given industry (e.g. b2b might scale in revenue much faster than people, but b2c might be scaling people faster at first)

> How much cash do they have on hand? How close are they to profitability?

Missing the most important one. **What is their burn - how long until they run out of money?**

> Are there any red flags (e.g. infighting, scandals, fast turnover)?

There are always some bad parts - no one is perfect. More important is _how_ they handle these situations and mitigate them.

> having a large sales team usually correlates with having a lot of customers to sell to

Large sales teams are not always a good thing, think its hard to say something one way or another.

> What are the company values, if they're codified somewhere?

Great question to ask the founders directly early on

> Equity

Link to Katie's blog post!

>  except that you don't get any until you've worked there a year

Make it clear that after that year, you get 25% all at once

> Negotiation

Also add in points about how you can find value-creating solutions that work for everyone, e.g. a bonus, raise, or equity bump after the next round is raised, if the company can't afford it now. Also mention that at some point, you want to make sure not to damage the relationship: assume best intent after some negotiation, and if they are never going to be in your range, don't force it. You don't want to start a new job where everyone involved (including you) regrets how it went down - don't forget the people you're negotiating with are your future coworkers.

> don't be afraid to be contrarian/play devil's advocate in your conversations about the business

I would explicitly advocate for this. Good founders can have thoughtful responses to any question about their business, even if they don't have the right answer (and have no problem admitting that). Bad founders will react negatively to this pushback.

**Comment by kimberli** [comment]
Thanks, as always! Addressed in [a2c632e](https://github.com/kimberli/new-grad-offers/commit/a2c632ebbdbc0de2fcee5f1a8c5015cbccfa6280) 😄❤️
